Repository fga-eps-mds/2020.2-Hortum-Mobile, pull requests merged in 2021-04, with the labels that each got.

#17 HOTFIX - Padronização dos arquivos
  hortum_mobile/lib/components/announcements_data.dart
  hortum_mobile/lib/components/footer.dart
  hortum_mobile/lib/components/form_validation.dart
  hortum_mobile/lib/data/announ_register_backend.dart
  hortum_mobile/lib/data/login_backend.dart
  hortum_mobile/lib/data/register_backend.dart
  hortum_mobile/lib/globals.dart
  hortum_mobile/lib/views/home_customer/components/carroussel.dart
  hortum_mobile/lib/views/home_customer/components/list_announcements.dart
  hortum_mobile/lib/views/home_customer/components/search.dart
  hortum_mobile/lib/views/home_customer/home_customer_page.dart
  hortum_mobile/lib/views/home_productor/components/buttons_row.dart
  hortum_mobile/lib/views/home_productor/components/categories.dart
  hortum_mobile/lib/views/home_productor/components/list_announcements.dart
  hortum_mobile/lib/views/home_productor/home_productor_page.dart
  hortum_mobile/lib/views/login/components/dialog_account_type.dart
  hortum_mobile/lib/views/login/components/forget_password.dart
  hortum_mobile/lib/views/login/components/form_field_login.dart
  hortum_mobile/lib/views/login/login_page.dart
  hortum_mobile/lib/views/login/services/login_services.dart
  hortum_mobile/lib/views/profile/components/add_picture.dart
  hortum_mobile/lib/views/profile/components/circle_style.dart
  hortum_mobile/lib/views/profile/components/logout_button.dart
  hortum_mobile/lib/views/profile/components/profile_form.dart
  hortum_mobile/lib/views/profile/components/profile_picture.dart
  hortum_mobile/lib/views/profile/profile.dart
  hortum_mobile/lib/views/profile/profile_page.dart
  hortum_mobile/lib/views/register/components/form_field.dart
  hortum_mobile/lib/views/register/components/register_form.dart
  hortum_mobile/lib/views/register_announcement/announcement_register_page.dart
  hortum_mobile/lib/views/register_announcement/components/announ_register_form.dart
  hortum_mobile/lib/views/register_announcement/services/register_announcements_services.dart
Labels: Frontend, Sprint 7, hotfix

#18 HOTFIX - Estilo PhotoSelect
  hortum_mobile/lib/components/photo_select.dart
  hortum_mobile/lib/views/register/components/register_form.dart
Labels: development, enhancement, hotfix

#19 #143 Adição do Hotfix template
  .github/ISSUE_TEMPLATE/hotfix_template.md
Labels: Sprint 8, documentation

#21 #20 Remoção do tema escuro
  hortum_mobile/lib/main.dart
  hortum_mobile/pubspec.yaml
Labels: Sprint 8, hotfix

#22 #141 Link anúncios HomeCustomerPage
  hortum_mobile/lib/data/announ_data_backend.dart
  hortum_mobile/lib/views/home_customer/components/list_announcements.dart
  hortum_mobile/lib/views/home_customer/home_customer_page.dart
  hortum_mobile/pubspec.yaml
Labels: Backend, Frontend, Sprint 8

#24 #95 [US09] - Excluir Anúncio
  hortum_mobile/lib/data/announ_delete_backend.dart
  hortum_mobile/lib/views/home_productor/components/buttons_row.dart
  hortum_mobile/lib/views/home_productor/components/dialog_confirm_delete.dart
  hortum_mobile/lib/views/home_productor/components/list_announcements.dart
Labels: Frontend, Sprint 8, development

#25 #144 implementação de CI
  .github/workflows/Flutter_CI.yml
Labels: DevOps, Sprint 8

#23 #142 Login Automatico
  hortum_mobile/lib/components/footer.dart
  hortum_mobile/lib/data/auto_login_backend.dart
  hortum_mobile/lib/model/user.dart
  hortum_mobile/lib/views/introScreen_page.dart
  hortum_mobile/pubspec.yaml
Labels: Frontend, Sprint 8, development

#26 #140 Testes
  hortum_mobile/lib/components/footer.dart
  hortum_mobile/lib/components/form_validation.dart
  hortum_mobile/lib/data/announ_delete_backend.dart
  hortum_mobile/lib/data/login_backend.dart
  hortum_mobile/lib/model/user.dart
  hortum_mobile/lib/views/home_customer/home_customer_page.dart
  hortum_mobile/lib/views/home_productor/components/dialog_confirm_delete.dart
  hortum_mobile/lib/views/login/components/dialog_account_type.dart
  hortum_mobile/lib/views/login/components/form_field_login.dart
  hortum_mobile/lib/views/login/login_page.dart
  hortum_mobile/lib/views/login/services/login_services.dart
  hortum_mobile/lib/views/profile/components/profile_form.dart
  hortum_mobile/lib/views/profile/profile_page.dart
  hortum_mobile/lib/views/register/components/register_form.dart
  hortum_mobile/lib/views/register_announcement/components/announ_register_form.dart
  hortum_mobile/lib/views/register_announcement/services/register_announcements_services.dart
  hortum_mobile/test/footer_test.dart
  hortum_mobile/test/form_validation_test.dart
  hortum_mobile/test/home_productor_page_test.dart
  hortum_mobile/test/login_page_test.dart
  hortum_mobile/test/register_announcements_test.dart
  hortum_mobile/test/user_test.dart
  hortum_mobile/test/widget_test.dart
Labels: Frontend, Sprint 8, enhancement

#29 Feature/162 codequality ci cd
  .github/workflows/Flutter_CI.yml
  hortum_mobile/analysis_options.yaml
  hortum_mobile/lib/components/photo_select.dart
  hortum_mobile/lib/data/announ_delete_backend.dart
  hortum_mobile/lib/data/register_backend.dart
  hortum_mobile/lib/views/home_productor/components/list_announcements.dart
  hortum_mobile/lib/views/login/login_page.dart
  hortum_mobile/pubspec.yaml
Labels: DevOps, Sprint 9, development

#28 #158 Refatorando rota de listar anúncios
  hortum_mobile/lib/data/announ_data_backend.dart
  hortum_mobile/lib/views/home_customer/components/list_announcements.dart
  hortum_mobile/test/announ_data_backend_test.dart
Labels: Frontend, Sprint 9, development

#30 #97 [US10/11] - Procurar Produto
  hortum_mobile/lib/data/announ_data_backend.dart
  hortum_mobile/lib/views/home_customer/components/home_type.dart
  hortum_mobile/lib/views/home_customer/components/list_announcements.dart
  hortum_mobile/lib/views/home_customer/components/search.dart
  hortum_mobile/lib/views/home_customer/home_customer_page.dart
Labels: Frontend, Sprint 9, development, user story

#31 #162 adicionando code coverage
  .github/workflows/Flutter_CI.yml
  README.md
  hortum_mobile/coverage/lcov.info
  hortum_mobile/pubspec.yaml
Labels: DevOps, Sprint 9

#32 #96 [US10] - Pesquisar Produtor
  hortum_mobile/lib/components/productors_box.dart
  hortum_mobile/lib/data/announ_data_backend.dart
  hortum_mobile/lib/data/announ_delete_backend.dart
  hortum_mobile/lib/data/announ_register_backend.dart
  hortum_mobile/lib/data/auto_login_backend.dart
  hortum_mobile/lib/data/login_backend.dart
  hortum_mobile/lib/data/productors_data_backend.dart
  hortum_mobile/lib/data/register_backend.dart
  hortum_mobile/lib/views/home_customer/components/list_announcements.dart
  hortum_mobile/lib/views/home_customer/components/list_productors.dart
  hortum_mobile/lib/views/home_customer/home_customer_page.dart
  hortum_mobile/lib/views/home_customer/services/home_customer_services.dart
  hortum_mobile/pubspec.yaml
  hortum_mobile/test/home_customer_page_test.dart
Labels: Frontend, Sprint 9, development, user story

#34 #92 [US06] - Atualizar Dados de Usuário
  hortum_mobile/lib/data/change_password_backend.dart
  hortum_mobile/lib/data/update_user_backend.dart
  hortum_mobile/lib/views/change_password/change_password_page.dart
  hortum_mobile/lib/views/change_password/components/password_form.dart
  hortum_mobile/lib/views/change_password/services/change_password_services.dart
  hortum_mobile/lib/views/profile/components/change_password_button.dart
  hortum_mobile/lib/views/profile/components/profile_form.dart
  hortum_mobile/lib/views/profile/profile_page.dart
  hortum_mobile/lib/views/profile/services/profile_services.dart
  hortum_mobile/lib/views/register/components/register_form.dart
  hortum_mobile/test/change_password_page_test.dart
  hortum_mobile/test/update_user_page_test.dart
Labels: Frontend, Sprint 9, development

#35 #94[US08] Editar Anúncio
  hortum_mobile/lib/components/announcements_data.dart
  hortum_mobile/lib/components/categories.dart
  hortum_mobile/lib/components/custom_desc_field.dart
  hortum_mobile/lib/components/form_field.dart
  hortum_mobile/lib/data/announ_edit_backend.dart
  hortum_mobile/lib/views/change_password/components/password_form.dart
  hortum_mobile/lib/views/edit_announ/components/edit_picture.dart
  hortum_mobile/lib/views/edit_announ/edit_page.dart
  hortum_mobile/lib/views/edit_announ/services/edit_announ_services.dart
  hortum_mobile/lib/views/home_productor/components/buttons_row.dart
  hortum_mobile/lib/views/home_productor/components/list_announcements.dart
  hortum_mobile/lib/views/profile/components/profile_form.dart
  hortum_mobile/lib/views/register/components/register_form.dart
  hortum_mobile/lib/views/register_announcement/components/announ_register_form.dart
  hortum_mobile/lib/views/register_announcement/components/select_field.dart
  hortum_mobile/test/edit_announ_test.dart
Labels: Frontend, Sprint 8, development

#33 #157 Homepage Produtor
  .github/workflows/Flutter_CI.yml
  hortum_mobile/coverage/lcov.info
  hortum_mobile/lib/data/prod_log_data_backend.dart
  hortum_mobile/lib/services/codec_string.dart
  hortum_mobile/lib/views/edit_announ/edit_page.dart
  hortum_mobile/lib/views/home_productor/components/buttons_row.dart
  hortum_mobile/lib/views/home_productor/components/list_announcements.dart
  hortum_mobile/lib/views/home_productor/home_productor_page.dart
  hortum_mobile/test/edit_announ_test.dart
  hortum_mobile/test/home_productor_page_test.dart
  hortum_mobile/test/services_test.dart
Labels: Frontend, Sprint 9, development

#36 #98 [US12] - Visualizar Anúncios de um Produtor
  hortum_mobile/lib/components/announcement_box.dart
  hortum_mobile/lib/components/circle_style.dart
  hortum_mobile/lib/components/productors_box.dart
  hortum_mobile/lib/components/profile_picture.dart
  hortum_mobile/lib/components/spin.dart
  hortum_mobile/lib/data/productor_details_backend.dart
  hortum_mobile/lib/services/codec_string.dart
  hortum_mobile/lib/views/change_password/change_password_page.dart
  hortum_mobile/lib/views/home_customer/components/list_announcements.dart
  hortum_mobile/lib/views/home_customer/components/list_productors.dart
  hortum_mobile/lib/views/home_customer/home_customer_page.dart
  hortum_mobile/lib/views/home_productor/components/list_announcements.dart
  hortum_mobile/lib/views/productor_details/components/announcements_details.dart
  hortum_mobile/lib/views/productor_details/components/announcements_tag.dart
  hortum_mobile/lib/views/productor_details/components/name_actions.dart
  hortum_mobile/lib/views/productor_details/components/productor_localization.dart
  hortum_mobile/lib/views/productor_details/productor_details.dart
  hortum_mobile/lib/views/productor_details/services/productor_details_services.dart
  hortum_mobile/lib/views/profile/components/profile_picture.dart
  hortum_mobile/lib/views/profile/profile_page.dart
  hortum_mobile/test/productor_details_test.dart
Labels: Frontend, Sprint 10, development, user story

#40 #38 Altreação da rota incorreta
  hortum_mobile/lib/data/prod_log_data_backend.dart
  hortum_mobile/test/home_productor_page_test.dart
Labels: Frontend, bug
