Repository fga-eps-mds/2020.2-Hortum-Mobile, pull requests merged in 2021-05, with the labels that each got.

#37 #161 Detalhes do Anúncio
  hortum_mobile/lib/components/announcement_box.dart
  hortum_mobile/lib/views/announcement_details/announcement_details_page.dart
  hortum_mobile/lib/views/announcement_details/components/custom_carrousel.dart
  hortum_mobile/lib/views/announcement_details/components/localization_container.dart
  hortum_mobile/lib/views/announcement_details/components/price_container.dart
  hortum_mobile/lib/views/announcement_details/components/title_buttons_row.dart
  hortum_mobile/lib/views/home_customer/components/list_announcements.dart
  hortum_mobile/lib/views/home_productor/components/list_announcements.dart
  hortum_mobile/lib/views/productor_details/services/productor_details_services.dart
  hortum_mobile/pubspec.yaml
  hortum_mobile/test/components/announcement_box_test.dart
  hortum_mobile/test/views/announcement_details/announcement_details_page_test.dart
Labels: Frontend, Sprint 10

#47 #204 Correção Tela Detalhes do Produtor
  hortum_mobile/lib/components/announcement_box.dart
  hortum_mobile/lib/components/productors_box.dart
  hortum_mobile/lib/views/announcement_details/announcement_details_page.dart
  hortum_mobile/lib/views/productor_details/components/announcements_details.dart
  hortum_mobile/lib/views/productor_details/components/name_actions.dart
  hortum_mobile/lib/views/productor_details/productor_details_page.dart
  hortum_mobile/lib/views/productor_details/services/productor_details_services.dart
  hortum_mobile/test/views/productor_details/productor_details_page_test.dart
  hortum_mobile/test/views/productor_details/services/productor_details_service_test.dart
Labels: Frontend, Sprint 12, bug, development

#45 #205 Refatorações na página de criar anúncio
  hortum_mobile/lib/components/custom_desc_field.dart
  hortum_mobile/lib/components/form_validation.dart
  hortum_mobile/lib/data/announcements/announcements_backend.dart
  hortum_mobile/lib/views/edit_announ/edit_page.dart
  hortum_mobile/lib/views/register_announcement/components/announ_register_form.dart
  hortum_mobile/lib/views/register_announcement/components/dialog_announ_error.dart
  hortum_mobile/lib/views/register_announcement/services/register_announcements_services.dart
  hortum_mobile/test/components/form_validation_test.dart
  hortum_mobile/test/views/register_announcement/services/register_announcement_services_test.dart
  hortum_mobile/test/views/register_announcement/services/register_announcements_services_test.dart
Labels: Frontend, Sprint 12, development

#50 [US05] Redefinir senha
  hortum_mobile/lib/views/login/components/dialog_forget_password.dart
  hortum_mobile/lib/views/login/components/forget_password.dart
  hortum_mobile/lib/views/login/components/form_field_login.dart
  hortum_mobile/lib/views/login/login_page.dart
  hortum_mobile/pubspec.yaml
  hortum_mobile/test/views/login/components/dialog_forget_password_test.dart
Labels: Frontend, Sprint 12, development, enhancement

#48 #182 Implementação Localização
  hortum_mobile/lib/components/dialog_empty_localizations.dart
  hortum_mobile/lib/components/form_validation.dart
  hortum_mobile/lib/components/localization_field.dart
  hortum_mobile/lib/data/announcements/announcements_backend.dart
  hortum_mobile/lib/views/edit_announ/edit_page.dart
  hortum_mobile/lib/views/edit_announ/services/edit_announ_services.dart
  hortum_mobile/lib/views/home_productor/components/buttons_row.dart
  hortum_mobile/lib/views/home_productor/components/list_announcements.dart
  hortum_mobile/lib/views/register_announcement/components/announ_register_form.dart
  hortum_mobile/lib/views/register_announcement/services/register_announcements_services.dart
  hortum_mobile/test/components/dialog_empty_localizations_test.dart
  hortum_mobile/test/data/announcements/announcements_backend_test.dart
  hortum_mobile/test/views/edit_announ/edit_page_test.dart
  hortum_mobile/test/views/edit_announ/services/edit_announ_services_test.dart
  hortum_mobile/test/views/home_productor/home_productor_page_test.dart
  hortum_mobile/test/views/register_announcement/services/register_announcements_services_test.dart
Labels: Frontend, Sprint 12, development, enhancement

#46 #27 [HOTFIX] - Dio
  hortum_mobile/lib/data/auto_login_backend.dart
  hortum_mobile/lib/views/introScreen_page.dart
  hortum_mobile/pubspec.yaml
Labels: Frontend, development, hotfix

#49 #206 Melhorias Gerais
  hortum_mobile/README.md
  hortum_mobile/android/app/src/main/AndroidManifest.xml
  hortum_mobile/android/app/src/main/res/mipmap-hdpi/ic_launcher.png
  hortum_mobile/android/app/src/main/res/mipmap-mdpi/ic_launcher.png
  hortum_mobile/android/app/src/main/res/mipmap-xhdpi/ic_launcher.png
  hortum_mobile/android/app/src/main/res/mipmap-xxhdpi/ic_launcher.png
  hortum_mobile/android/app/src/main/res/mipmap-xxxhdpi/ic_launcher.png
  hortum_mobile/assets/images/logo.png
  hortum_mobile/ios/Runner.xcodeproj/project.pbxproj
  hortum_mobile/ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-1024x1024@1x.png
  hortum_mobile/ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-20x20@1x.png
  hortum_mobile/ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-20x20@2x.png
  hortum_mobile/ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-20x20@3x.png
  hortum_mobile/ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-29x29@1x.png
  hortum_mobile/ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-29x29@2x.png
  hortum_mobile/ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-29x29@3x.png
  hortum_mobile/ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-40x40@1x.png
  hortum_mobile/ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-40x40@2x.png
  hortum_mobile/ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-40x40@3x.png
  hortum_mobile/ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-60x60@2x.png
  hortum_mobile/ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-60x60@3x.png
  hortum_mobile/ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-76x76@1x.png
  hortum_mobile/ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-76x76@2x.png
  hortum_mobile/ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-83.5x83.5@2x.png
  hortum_mobile/ios/Runner/Info.plist
  hortum_mobile/lib/main.dart
  hortum_mobile/lib/views/introScreen_page.dart
  hortum_mobile/pubspec.yaml
Labels: Frontend, Sprint 12, enhancement

#51 #194 Adição do numero de telefone
  hortum_mobile/lib/components/form_validation.dart
  hortum_mobile/lib/data/login_backend.dart
  hortum_mobile/lib/data/register_backend.dart
  hortum_mobile/lib/data/user_data_backend.dart
  hortum_mobile/lib/model/user.dart
  hortum_mobile/lib/views/profile/components/profile_form.dart
  hortum_mobile/lib/views/profile/profile_page.dart
  hortum_mobile/lib/views/profile/services/profile_services.dart
  hortum_mobile/lib/views/register/components/dialog_email_enviado.dart
  hortum_mobile/lib/views/register/components/dialog_erro_cadastrado.dart
  hortum_mobile/lib/views/register/components/register_form.dart
  hortum_mobile/lib/views/register/services/register_services.dart
  hortum_mobile/test/components/form_validation_test.dart
  hortum_mobile/test/data/user_data_backend_test.dart
  hortum_mobile/test/views/profile/components/profile_form_test.dart
  hortum_mobile/test/views/profile/services/profile_services_test.dart
  hortum_mobile/test/views/register/register_page_test.dart
  hortum_mobile/test/views/register/services/register_services_test.dart
Labels: Frontend, Sprint 11, development

#56 #55 [BUG] Preço anúncio
  hortum_mobile/lib/views/edit_announ/edit_page.dart
  hortum_mobile/lib/views/register_announcement/components/announ_register_form.dart
Labels: bug

#54 #224 Mudança visual Footer
  hortum_mobile/lib/components/footer.dart
  hortum_mobile/lib/views/productor_details/components/announcements_details.dart
Labels: Frontend, Sprint 13, development

#58 #223 Trocando iplocal pelo ip heroku
  hortum_mobile/lib/data/announcements/announcements_backend.dart
  hortum_mobile/lib/data/auto_login_backend.dart
  hortum_mobile/lib/data/complaint_data_backend.dart
  hortum_mobile/lib/data/login_backend.dart
  hortum_mobile/lib/data/prod_log_data_backend.dart
  hortum_mobile/lib/data/productor_details_backend.dart
  hortum_mobile/lib/data/productors_data_backend.dart
  hortum_mobile/lib/data/register_backend.dart
  hortum_mobile/lib/data/user_data_backend.dart
  hortum_mobile/lib/globals.dart
  hortum_mobile/lib/views/login/components/dialog_forget_password.dart
  hortum_mobile/test/data/announcements/announcements_backend_test.dart
  hortum_mobile/test/views/home_customer/home_customer_page_test.dart
  hortum_mobile/test/views/register_complaint/services/complaint_services_test.dart
Labels: Sprint 13, hotfix

#42 #103/104 [US17/18] - Favoritar Anúncio e Produtor
  hortum_mobile/lib/components/announcement_box.dart
  hortum_mobile/lib/components/footer.dart
  hortum_mobile/lib/components/list_announcements.dart
  hortum_mobile/lib/components/productors_box.dart
  hortum_mobile/lib/data/announ_favorite_backend.dart
  hortum_mobile/lib/data/announcements/announcements_backend.dart
  hortum_mobile/lib/data/productor_favorite_backend.dart
  hortum_mobile/lib/data/productors_data_backend.dart
  hortum_mobile/lib/views/favorites/components/select_favorite_button.dart
  hortum_mobile/lib/views/favorites/fav_page.dart
  hortum_mobile/lib/views/favorites/services/fav_page_services.dart
  hortum_mobile/lib/views/home_customer/components/list_productors.dart
  hortum_mobile/lib/views/home_customer/home_customer_page.dart
  hortum_mobile/lib/views/home_productor/components/list_announcements.dart
  hortum_mobile/lib/views/productor_details/services/productor_details_services.dart
  hortum_mobile/test/components/announcement_box_test.dart
  hortum_mobile/test/data/announ_favorite_backend_test.dart
  hortum_mobile/test/data/announcements/announcements_backend_test.dart
  hortum_mobile/test/data/productor_favorite_backend_test.dart
  hortum_mobile/test/views/favorites/fav_test.dart
  hortum_mobile/test/views/productor_details/services/productor_details_service_test.dart
Labels: Frontend, Sprint 10, development, user story

#60 #238 Adição do telefone na página de detalhes do produtor
  hortum_mobile/lib/components/announcement_box.dart
  hortum_mobile/lib/components/list_announcements.dart
  hortum_mobile/lib/components/productors_box.dart
  hortum_mobile/lib/views/announcement_details/announcement_details_page.dart
  hortum_mobile/lib/views/home_customer/components/home_type.dart
  hortum_mobile/lib/views/home_customer/components/list_productors.dart
  hortum_mobile/lib/views/home_productor/components/list_announcements.dart
  hortum_mobile/lib/views/productor_details/components/phone_number_box.dart
  hortum_mobile/lib/views/productor_details/productor_details_page.dart
  hortum_mobile/lib/views/productor_details/services/productor_details_services.dart
  hortum_mobile/test/components/announcement_box_test.dart
  hortum_mobile/test/views/announcement_details/announcement_details_page_test.dart
  hortum_mobile/test/views/productor_details/productor_details_page_test.dart
Labels: Frontend, Sprint 14, development, enhancement

#59 #208 Atualização das categorias
  hortum_mobile/assets/images/acucar.jpg
  hortum_mobile/assets/images/artesanato.jpg
  hortum_mobile/assets/images/bebidas.jpeg
  hortum_mobile/assets/images/cafe.jpeg
  hortum_mobile/assets/images/cana.jpg
  hortum_mobile/assets/images/carne.jpg
  hortum_mobile/assets/images/cogumelos.jpg
  hortum_mobile/assets/images/congelados.jpg
  hortum_mobile/assets/images/defumados.jpg
  hortum_mobile/assets/images/desidratados.jpeg
  hortum_mobile/assets/images/doces.jpg
  hortum_mobile/assets/images/flores.jpg
  hortum_mobile/assets/images/frango.jpg
  hortum_mobile/assets/images/frutas.jpeg
  hortum_mobile/assets/images/graos.jpeg
  hortum_mobile/assets/images/hortalicas.jpg
  hortum_mobile/assets/images/laticinios.jpg
  hortum_mobile/assets/images/legumes.jpeg
  hortum_mobile/assets/images/mandioca.jpg
  hortum_mobile/assets/images/outros.jpg
  hortum_mobile/assets/images/ovos.jpeg
  hortum_mobile/assets/images/peixe.jpg
  hortum_mobile/assets/images/polpa.jpg
  hortum_mobile/assets/images/sorvetes.jpeg
  hortum_mobile/assets/images/trigo.jpg
  hortum_mobile/lib/components/announcements_data.dart
  hortum_mobile/lib/components/categories.dart
  hortum_mobile/lib/data/announcements/announcements_backend.dart
  hortum_mobile/lib/views/filtered_announcements_categories/filtered_announcements_categories_page.dart
  hortum_mobile/lib/views/filtered_announcements_categories/services/filtered_announcements_services.dart
  hortum_mobile/lib/views/home_customer/components/carroussel.dart
  hortum_mobile/lib/views/home_customer/home_customer_page.dart
  hortum_mobile/test/views/edit_announ/edit_page_test.dart
  hortum_mobile/test/views/filtered_announcement_categorry/filtered_announcement_category_page_test.dart
  hortum_mobile/test/views/home_productor/home_productor_page_test.dart
Labels: Frontend, Sprint 13
