Repository fga-eps-mds/2020.2-Hortum-Mobile, pull requests merged in 2021-03, with the labels that each got.

#3 #78 Melhoria dos README's
  README.md
Labels: Sprint 5, documentation

#4 #61/#83 [US] - Frontend do cadastro de usuário
  hortum_mobile/android/app/src/main/AndroidManifest.xml
  hortum_mobile/assets/fonts/Comfortaa-Bold.ttf
  hortum_mobile/assets/fonts/Comfortaa-Light.ttf
  hortum_mobile/assets/fonts/Comfortaa-Medium.ttf
  hortum_mobile/assets/fonts/Comfortaa-Regular.ttf
  hortum_mobile/assets/fonts/Comfortaa-SemiBold.ttf
  hortum_mobile/assets/fonts/Roboto-Bold.ttf
  hortum_mobile/assets/fonts/Roboto-Light.ttf
  hortum_mobile/assets/fonts/Roboto-Medium.ttf
  hortum_mobile/assets/fonts/Roboto-Regular.ttf
  hortum_mobile/lib/data/register_backend.dart
  hortum_mobile/lib/globals.dart
  hortum_mobile/lib/main.dart
  hortum_mobile/lib/view/features/register/components/form_field..dart
  hortum_mobile/lib/view/features/register/components/register_form.dart
  hortum_mobile/lib/view/features/register/page/register_page.dart
  hortum_mobile/pubspec.lock
  hortum_mobile/pubspec.yaml
Labels: Frontend, Sprint 4, development, enhancement

#5 #81 [US03] Frontend do Login de Conta
  hortum_mobile/.gitignore
  hortum_mobile/android/app/build.gradle
  hortum_mobile/android/app/src/profile/AndroidManifest.xml
  hortum_mobile/assets/images/logo.png
  hortum_mobile/lib/data/login_backend.dart
  hortum_mobile/lib/data/register_backend.dart
  hortum_mobile/lib/globals.dart
  hortum_mobile/lib/main.dart
  hortum_mobile/lib/model/userToken.dart
  hortum_mobile/lib/view/features/introScreen_page.dart
  hortum_mobile/lib/view/features/login/login_page.dart
  hortum_mobile/lib/view/features/register/components/form_field.dart
  hortum_mobile/lib/view/features/register/components/register_form.dart
  hortum_mobile/pubspec.lock
  hortum_mobile/pubspec.yaml
  hortum_mobile/test/widget_test.dart
Labels: Frontend, Sprint 5, development, enhancement

#6 #113 Criando rota para cadastro de produtor e comprador
  hortum_mobile/lib/data/register_backend.dart
  hortum_mobile/lib/view/features/login/login_page.dart
  hortum_mobile/lib/view/features/register/components/register_form.dart
  hortum_mobile/lib/view/features/register/page/register_page.dart
Labels: Sprint 6, enhancement

#7 #114 Telas Principais
  hortum_mobile/assets/images/banana.jpg
  hortum_mobile/assets/images/brocolis.jpg
  hortum_mobile/assets/images/cenoura.jpeg
  hortum_mobile/assets/images/morango.jpg
  hortum_mobile/assets/images/perfil.jpg
  hortum_mobile/assets/images/tomate.jpg
  hortum_mobile/lib/components/announcement_box.dart
  hortum_mobile/lib/components/footer.dart
  hortum_mobile/lib/data/login_backend.dart
  hortum_mobile/lib/globals.dart
  hortum_mobile/lib/main.dart
  hortum_mobile/lib/model/user.dart
  hortum_mobile/lib/views/home_customer/components/categories.dart
  hortum_mobile/lib/views/home_customer/home_customer_page.dart
  hortum_mobile/lib/views/home_productor/components/categories.dart
  hortum_mobile/lib/views/home_productor/home_productor_page.dart
  hortum_mobile/lib/views/introScreen_page.dart
  hortum_mobile/lib/views/login/login_page.dart
  hortum_mobile/lib/views/register/components/form_field.dart
  hortum_mobile/lib/views/register/components/register_form.dart
  hortum_mobile/lib/views/register/page/register_page.dart
Labels: Frontend, Sprint 6, development, enhancement

#8 #117 Tela Meu Perfil
  hortum_mobile/lib/components/footer.dart
  hortum_mobile/lib/data/login_backend.dart
  hortum_mobile/lib/model/user.dart
  hortum_mobile/lib/views/login/login_page.dart
  hortum_mobile/lib/views/profile/profile.dart
  hortum_mobile/lib/views/register/register_page.dart
Labels: Frontend, Sprint 6, development, enhancement

#9 #93 [US07] Cadastro de Anúnio
  hortum_mobile/lib/components/categories.dart
  hortum_mobile/lib/components/confirm_button.dart
  hortum_mobile/lib/components/form_field.dart
  hortum_mobile/lib/components/photo_select.dart
  hortum_mobile/lib/data/announ_register_backend.dart
  hortum_mobile/lib/views/introScreen_page.dart
  hortum_mobile/lib/views/login/login_page.dart
  hortum_mobile/lib/views/register/components/register_form.dart
  hortum_mobile/lib/views/register/register_page.dart
  hortum_mobile/lib/views/register_announcement/components/announ_register_form.dart
  hortum_mobile/lib/views/register_announcement/components/select_field.dart
  hortum_mobile/lib/views/register_announcement/page/announcement_register_page.dart
Labels: Frontend, Sprint 6, development, user story

#10 #131[Hotfix]Navbar produtor
  hortum_mobile/lib/components/footer.dart
Labels: Frontend, Sprint 7, development, enhancement

#12 #11 [hotfix] Correção de erro de registro de anúncios
  hortum_mobile/lib/data/login_backend.dart
Labels: Frontend, bug

#13 #90 [US04] Sair da Conta
  hortum_mobile/lib/model/user.dart
  hortum_mobile/lib/views/profile/profile.dart
Labels: Sprint 7, development, user story
